// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZRY9nyQDzJcKNoJDq5ir_9DpG6Pd1QDw',
    appId: '1:1059061669548:web:6b34a425432f041a504909',
    messagingSenderId: '1059061669548',
    projectId: 'slideshow-fd4a8',
    authDomain: 'slideshow-fd4a8.firebaseapp.com',
    storageBucket: 'slideshow-fd4a8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ5n1IvdSe9xHtNPiEtAq3KZhMAz4xA1s',
    appId: '1:1059061669548:android:02ca062c4430fa44504909',
    messagingSenderId: '1059061669548',
    projectId: 'slideshow-fd4a8',
    storageBucket: 'slideshow-fd4a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4Fekl6eFFlfomxLtZjGONo-KZG9Jfz2Q',
    appId: '1:1059061669548:ios:ba64374d7a5f64ea504909',
    messagingSenderId: '1059061669548',
    projectId: 'slideshow-fd4a8',
    storageBucket: 'slideshow-fd4a8.appspot.com',
    iosBundleId: 'com.example.slideshow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4Fekl6eFFlfomxLtZjGONo-KZG9Jfz2Q',
    appId: '1:1059061669548:ios:b820b2746ea47272504909',
    messagingSenderId: '1059061669548',
    projectId: 'slideshow-fd4a8',
    storageBucket: 'slideshow-fd4a8.appspot.com',
    iosBundleId: 'com.example.slideshow.RunnerTests',
  );
}
